apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/rollout
- store-service-export-central1.yaml
- store-gateway-preferred.yaml
- store-route-preferred.yaml
- store-backend-policy.yaml



