apiVersion: v1
kind: Namespace
metadata:
  name: store
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: store
  namespace: store
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: store
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {} # Pause indefinitely until promoted
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 75
      - pause: {duration: 30s}
---
apiVersion: v1
kind: Service
metadata:
  name: store-weighted-lb
  namespace: store
  annotations:
    networking.gke.io/weighted-load-balancing: "pods-per-node"
spec:
  type: LoadBalancer
  loadBalancerClass: "networking.gke.io/l4-regional-external"
  externalTrafficPolicy: Local
  selector:
    app: store
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
