kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: store-gateway-preferred
  namespace: store
  labels:
    app: store
    reconcile-trigger: "2"
spec:
  gatewayClassName: gke-l7-global-external-managed-mc
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
