apiVersion: v1
kind: Namespace
metadata:
  name: store
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: store
  namespace: store
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: store
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0
        ports:
        - containerPort: 8080
        env:
        - name: TEST_UPDATE
          value: "run-7"
  strategy:
    blueGreen:
      activeService: store
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: store
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: store
  namespace: store
